blank_issues_enabled: false
contact_links:
    - name: Contact René Weiberlenn
      url: rene.weiberlenn@live.de
      about: Feel free to contact me if you have any questions or suggestions. I will try to respond as soon as possible.
